name: Matrix

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ozh: ["nice", "cool"]
        stuff: [1, 2]

    steps:
    - name: One step
      run: echo "${{ matrix.ozh }} / ${{ matrix.stuff }}"
