name: Test PECL

on:
  workflow_dispatch:

jobs:
  test:
    name: PHP
    runs-on: ubuntu-latest

    steps:
    - name: Use PHP 8
      uses: shivammathur/setup-php@2.18.1
      with:
        php-version: '8.0'
        extensions: mbstring, curl, zip, dom, simplexml, intl, pdo_mysql, pecl_http
        tools: pecl

    - name: Test
      run: |
        php --version
        php -m
        php -r "print_r(get_loaded_extensions());"
        php -r 'var_dump(function_exists("http_build_url"));';
        

